name = "developer-tools"
compatibility_date = "2025-10-25"

[build]
command = "cd apps/dev-tools && pnpm install && pnpm run build"
pages_build_output_dir = "apps/dev-tools/dist"

# 正确的环境变量配置方式
[env.production]
NODE_ENV = "production"

# 或者使用 vars 表（如果支持）
[env.production.vars]
NODE_ENV = "production"