export const {
    DEV: IS_DEV,
    PROD: IS_PROD,
    TEST: IS_TEST,
    VITE_API_URL,
    VITE_APP_TITLE = 'AutoParseHDCShell',
    VITE_APP_SHORT_NAME = 'APHDCS',
    VITE_APP_VERSION = '0.0.1',
    VITE_GA_ID = '',
    VITE_BAIDU_TJ_ID = '',
    VITE_UMENG_ID = '',
    VITE_APP_DESCRIPTION = 'AutoParseHDCShell - A powerful tool for parsing HDCShell links.',
    VITE_APP_KEYWORDS = 'AutoParseHDCShell, HDCShell, Link Parser, 免费解析, 多平台支持',
    VITE_APP_AUTHOR = 'yonjay',
    VITE_APP_LICENSE = 'MIT',
    VITE_APP_COPYRIGHT = '2025-now yonjay',
    VITE_APP_THIRD_PARTY = 'React, Vite, TailwindCSS, shadcn/ui, etc.',
    VITE_APP_PROXY = '/api',
    VITE_APP_STATIC = '/static/',
    VITE_APP_ICP = '',
    VITE_APP_GOV_ICP = '',
    VITE_APP_PUBLIC_SECURITY = '',
    VITE_APP_BUILD_TIME = new Date().toISOString(),
    VITE_APP_BUILD_BY = 'yonjay',
} = import.meta.env
